GET http://localhost:3001/api/notes
###
GET http://localhost:3001/api/notes/7
###
POST http://localhost:3001/api/notes
Content-Type: application/json

{
    "content" : "vs code rest client is a prety handy tool",
    "important": false
}
###
POST http://localhost:3001/api/notes/ HTTP/1.1
content-type: application/json

{
    "name": "sample",
    "time": "Wed, 21 Oct 2015 18:27:50 GMT"
}
###
DELETE http://localhost:3001/api/notes/6
###
### test choi choi 